import { access, mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { homedir } from "node:os";
import { fileURLToPath } from "node:url";
import packageJson from "../../../package.json" with { type: "json" };

export type PiExtensionCommandOptions = {
  local?: boolean;
  binaryPath?: string;
  nodePath?: string;
};

export type InstallPiExtensionResult = {
  extensionPath: string;
  backupPath?: string;
};

export type UninstallPiExtensionResult = {
  extensionPath: string;
  backupPath?: string;
  removed: boolean;
  restoredBackup: boolean;
};

export type PiDoctorReport = {
  extensionPath: string;
  status: "ok" | "warn" | "broken" | "disabled";
  issues: string[];
  fixCommand: string;
  checkedPaths: string[];
  missingPaths: string[];
};

type PiExtensionRuntimeConfig = {
  extensionCommand: string;
};

const TOKENJUICE_PI_EXTENSION_COMMAND = "tj";
const LEGACY_PI_RUNTIME_BASENAME = "tokenjuice-runtime.js";
const TOKENJUICE_PI_FIX_COMMAND = "tokenjuice install pi";

function getPiAgentDir(): string {
  return process.env.PI_CODING_AGENT_DIR || join(homedir(), ".pi", "agent");
}

function getDefaultExtensionPath(): string {
  return join(getPiAgentDir(), "extensions", "tokenjuice.js");
}

function buildPiExtensionSource(runtimeSource: string, config: PiExtensionRuntimeConfig): string {
  return String.raw`/**
 * tokenjuice pi extension
 * generated by tokenjuice v${packageJson.version}
 */

${runtimeSource}

const config = ${JSON.stringify(config, null, 2)};

export default createTokenjuicePiExtension(config);
`;
}

async function resolvePiRuntimeEntryPoint(): Promise<string> {
  const candidates = [
    fileURLToPath(new URL("./extension/runtime.ts", import.meta.url)),
    fileURLToPath(new URL("../../../src/hosts/pi/extension/runtime.ts", import.meta.url)),
  ];

  for (const candidate of candidates) {
    try {
      await access(candidate);
      return candidate;
    } catch {
      continue;
    }
  }

  throw new Error(`unable to resolve pi runtime source entrypoint from ${candidates.join(", ")}`);
}

async function bundlePiExtensionRuntimeSource(): Promise<string> {
  let esbuild;
  try {
    esbuild = await import("esbuild");
  } catch (error) {
    throw new Error(`unable to load esbuild to bundle the pi runtime from source: ${String(error)}`);
  }

  const entryPoint = await resolvePiRuntimeEntryPoint();
  const result = await esbuild.build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "esm",
    platform: "node",
    target: "node20",
    write: false,
  });

  const runtimeSource = result.outputFiles[0]?.text;
  if (!runtimeSource) {
    throw new Error("failed to bundle the pi runtime: esbuild produced no output");
  }

  return runtimeSource;
}

async function loadPiExtensionRuntimeSource(local = false): Promise<string> {
  if (local) {
    return await bundlePiExtensionRuntimeSource();
  }

  const runtimeAssetUrl = new URL("./extension/runtime.js", import.meta.url);

  try {
    return await readFile(runtimeAssetUrl, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
  }

  return await bundlePiExtensionRuntimeSource();
}

async function writeAtomically(path: string, content: string): Promise<void> {
  const tempPath = `${path}.tmp`;
  await writeFile(tempPath, content, { encoding: "utf8", mode: 0o600 });
  await rename(tempPath, path);
}

async function chooseBackupPath(filePath: string): Promise<string> {
  for (let index = 0; ; index += 1) {
    const candidate = index === 0 ? `${filePath}.bak` : `${filePath}.bak.${index}`;
    try {
      await access(candidate);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        return candidate;
      }
      throw error;
    }
  }
}

async function removeLegacyRuntimeFile(extensionPath: string): Promise<void> {
  const legacyRuntimePath = join(dirname(extensionPath), LEGACY_PI_RUNTIME_BASENAME);
  try {
    await rm(legacyRuntimePath);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
  }
}

function isTokenjuiceGeneratedPiExtension(source: string): boolean {
  return source.includes("generated by tokenjuice v") && source.includes("createTokenjuicePiExtension");
}

async function findRestorableBackup(extensionPath: string): Promise<{ backupPath: string; source: string } | undefined> {
  let latest: { backupPath: string; source: string } | undefined;
  for (let index = 0; ; index += 1) {
    const backupPath = index === 0 ? `${extensionPath}.bak` : `${extensionPath}.bak.${index}`;
    try {
      const source = await readFile(backupPath, "utf8");
      if (!isTokenjuiceGeneratedPiExtension(source)) {
        latest = { backupPath, source };
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        return latest;
      }
      throw error;
    }
  }
}

export async function installPiExtension(
  extensionPath = getDefaultExtensionPath(),
  options: PiExtensionCommandOptions = {},
): Promise<InstallPiExtensionResult> {
  const runtimeConfig: PiExtensionRuntimeConfig = {
    extensionCommand: TOKENJUICE_PI_EXTENSION_COMMAND,
  };
  const runtimeSource = await loadPiExtensionRuntimeSource(Boolean(options.local));
  const extensionSource = buildPiExtensionSource(runtimeSource, runtimeConfig);

  await mkdir(dirname(extensionPath), { recursive: true });

  let backupPath: string | undefined;
  try {
    const existing = await readFile(extensionPath, "utf8");
    backupPath = await chooseBackupPath(extensionPath);
    await writeFile(backupPath, existing, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
  }

  await removeLegacyRuntimeFile(extensionPath);
  await writeAtomically(extensionPath, extensionSource);

  return {
    extensionPath,
    ...(backupPath ? { backupPath } : {}),
  };
}

export async function uninstallPiExtension(
  extensionPath = getDefaultExtensionPath(),
): Promise<UninstallPiExtensionResult> {
  let source: string;
  try {
    source = await readFile(extensionPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return { extensionPath, removed: false, restoredBackup: false };
    }
    throw error;
  }

  if (!isTokenjuiceGeneratedPiExtension(source)) {
    return { extensionPath, removed: false, restoredBackup: false };
  }

  await removeLegacyRuntimeFile(extensionPath);

  const restorableBackup = await findRestorableBackup(extensionPath);
  if (restorableBackup) {
    await writeAtomically(extensionPath, restorableBackup.source);
    return { extensionPath, backupPath: restorableBackup.backupPath, removed: true, restoredBackup: true };
  }

  await rm(extensionPath);
  return { extensionPath, removed: true, restoredBackup: false };
}

export async function doctorPiExtension(extensionPath = getDefaultExtensionPath()): Promise<PiDoctorReport> {
  let source: string;
  try {
    source = await readFile(extensionPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return {
        extensionPath,
        status: "disabled",
        issues: [],
        fixCommand: TOKENJUICE_PI_FIX_COMMAND,
        checkedPaths: [],
        missingPaths: [],
      };
    }

    return {
      extensionPath,
      status: "broken",
      issues: [`tokenjuice pi extension could not be read: ${String(error)}`],
      fixCommand: TOKENJUICE_PI_FIX_COMMAND,
      checkedPaths: [extensionPath],
      missingPaths: [],
    };
  }

  if (!isTokenjuiceGeneratedPiExtension(source)) {
    return {
      extensionPath,
      status: "disabled",
      issues: [],
      fixCommand: TOKENJUICE_PI_FIX_COMMAND,
      checkedPaths: [],
      missingPaths: [],
    };
  }
  const issues: string[] = [];
  if (source.includes(LEGACY_PI_RUNTIME_BASENAME)) {
    issues.push("installed pi extension still references the legacy sibling runtime");
  }

  return {
    extensionPath,
    status: issues.length > 0 ? "warn" : "ok",
    issues,
    fixCommand: TOKENJUICE_PI_FIX_COMMAND,
    checkedPaths: [extensionPath],
    missingPaths: [],
  };
}
