import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import { afterEach, describe, expect, it } from "vitest";

import {
  doctorOpenCodeExtension,
  installOpenCodeExtension,
  uninstallOpenCodeExtension,
} from "../../src/index.js";

const tempDirs: string[] = [];
const originalOpenCodeConfigDir = process.env.OPENCODE_CONFIG_DIR;
const originalXdgConfigHome = process.env.XDG_CONFIG_HOME;
const originalHome = process.env.HOME;

afterEach(async () => {
  if (originalOpenCodeConfigDir === undefined) {
    delete process.env.OPENCODE_CONFIG_DIR;
  } else {
    process.env.OPENCODE_CONFIG_DIR = originalOpenCodeConfigDir;
  }
  if (originalXdgConfigHome === undefined) {
    delete process.env.XDG_CONFIG_HOME;
  } else {
    process.env.XDG_CONFIG_HOME = originalXdgConfigHome;
  }
  if (originalHome === undefined) {
    delete process.env.HOME;
  } else {
    process.env.HOME = originalHome;
  }
  await Promise.all(tempDirs.splice(0).map((dir) => rm(dir, { recursive: true, force: true })));
});

async function createTempDir(): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), "tokenjuice-opencode-test-"));
  tempDirs.push(dir);
  return dir;
}

async function readOptional(path: string | URL): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return undefined;
    }
    throw error;
  }
}

type FakeToolInput = {
  tool: string;
  sessionID: string;
  callID: string;
  args: Record<string, unknown>;
};

type FakeToolOutput = {
  title: string;
  output: string;
  metadata: Record<string, unknown>;
};

async function loadInstalledHook(extensionPath: string) {
  const importUrl = `${pathToFileURL(extensionPath).href}?t=${Date.now()}-${Math.random()}`;
  const imported = await import(importUrl);
  expect(typeof imported.default).toBe("function");
  const hooks = await imported.default({});
  expect(typeof hooks?.["tool.execute.after"]).toBe("function");
  return hooks["tool.execute.after"] as (input: FakeToolInput, output: FakeToolOutput) => Promise<void>;
}

describe("installOpenCodeExtension", () => {
  it("reports a disabled opencode integration when no extension is installed", async () => {
    const home = await createTempDir();
    const configDir = join(home, "opencode-config");

    process.env.OPENCODE_CONFIG_DIR = configDir;
    const report = await doctorOpenCodeExtension();

    expect(report.status).toBe("disabled");
    expect(report.extensionPath).toBe(join(configDir, "plugins", "tokenjuice.js"));
    expect(report.issues).toEqual([]);
  });

  it("installs a single-file opencode plugin under OPENCODE_CONFIG_DIR", async () => {
    const home = await createTempDir();
    const configDir = join(home, "opencode-config");
    process.env.OPENCODE_CONFIG_DIR = configDir;

    const result = await installOpenCodeExtension(undefined, { local: true });
    const extensionSource = await readFile(result.extensionPath, "utf8");

    expect(result.extensionPath).toBe(join(configDir, "plugins", "tokenjuice.js"));
    expect(result.backupPath).toBeUndefined();
    expect(extensionSource).toContain("createTokenjuiceOpenCodeExtension");
    expect(extensionSource).toContain("generated by tokenjuice v");
    expect(extensionSource).toContain("export default");
  });

  it("backs up an existing opencode plugin before overwriting it", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await writeFile(extensionPath, "// old plugin\n", "utf8");

    const result = await installOpenCodeExtension(extensionPath, { local: true });

    expect(result.backupPath).toBe(`${extensionPath}.bak`);
    expect(await readFile(`${extensionPath}.bak`, "utf8")).toBe("// old plugin\n");
  });

  it("reports an installed opencode plugin as healthy", async () => {
    const home = await createTempDir();
    const configDir = join(home, "opencode-config");
    process.env.OPENCODE_CONFIG_DIR = configDir;

    await installOpenCodeExtension(undefined, { local: true });
    const report = await doctorOpenCodeExtension();

    expect(report.status).toBe("ok");
    expect(report.extensionPath).toBe(join(configDir, "plugins", "tokenjuice.js"));
    expect(report.issues).toEqual([]);
  });

  it("uninstalls the opencode plugin", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");

    await installOpenCodeExtension(extensionPath, { local: true });
    expect(await readOptional(extensionPath)).toBeDefined();

    const uninstallResult = await uninstallOpenCodeExtension(extensionPath);

    expect(uninstallResult.removed).toBe(true);
    expect(await readOptional(extensionPath)).toBeUndefined();
  });

  it("reports removed=false when uninstalling a non-existent plugin", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");

    const uninstallResult = await uninstallOpenCodeExtension(extensionPath);

    expect(uninstallResult.removed).toBe(false);
    expect(uninstallResult.extensionPath).toBe(extensionPath);
  });

  it("respects XDG_CONFIG_HOME when OPENCODE_CONFIG_DIR is unset", async () => {
    const xdg = await createTempDir();
    delete process.env.OPENCODE_CONFIG_DIR;
    process.env.XDG_CONFIG_HOME = xdg;

    const report = await doctorOpenCodeExtension();

    expect(report.extensionPath).toBe(join(xdg, "opencode", "plugins", "tokenjuice.js"));
  });

  it("falls back to $HOME/.config/opencode when neither OPENCODE_CONFIG_DIR nor XDG_CONFIG_HOME is set", async () => {
    const home = await createTempDir();
    delete process.env.OPENCODE_CONFIG_DIR;
    delete process.env.XDG_CONFIG_HOME;
    process.env.HOME = home;

    const report = await doctorOpenCodeExtension();

    expect(report.extensionPath).toBe(join(home, ".config", "opencode", "plugins", "tokenjuice.js"));
  });
});

describe("opencode runtime hook", () => {
  it("ignores non-bash tools", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const output: FakeToolOutput = {
      title: "",
      output: "hello from read tool",
      metadata: {},
    };

    await hook(
      {
        tool: "read",
        sessionID: "s1",
        callID: "c1",
        args: { path: "foo.txt" },
      },
      output,
    );

    expect(output.output).toBe("hello from read tool");
    expect(output.metadata.tokenjuice).toBeUndefined();
  });

  it("no-ops on empty bash output", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const output: FakeToolOutput = {
      title: "",
      output: "",
      metadata: {},
    };

    await hook(
      {
        tool: "bash",
        sessionID: "s1",
        callID: "c1",
        args: { command: "true" },
      },
      output,
    );

    expect(output.output).toBe("");
    expect(output.metadata.tokenjuice).toBeUndefined();
  });

  it("compacts git status output in-process and attaches metadata", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const output: FakeToolOutput = {
      title: "",
      output: [
        "On branch feat/opencode-adapter",
        "",
        "Changes not staged for commit:",
        "\tmodified:   src/hosts/opencode/index.ts",
        "\tmodified:   src/hosts/opencode/extension/runtime.ts",
        "",
        "no changes added to commit",
      ].join("\n"),
      metadata: {},
    };

    await hook(
      {
        tool: "bash",
        sessionID: "s1",
        callID: "c1",
        args: { command: "git status" },
      },
      output,
    );

    expect(output.output).toContain("M: src/hosts/opencode/index.ts");
    expect(output.output).toContain("tokenjuice compacted bash output");
    const tokenjuice = output.metadata.tokenjuice as Record<string, unknown> | undefined;
    expect(tokenjuice?.compacted).toBe(true);
    expect(typeof tokenjuice?.rawChars).toBe("number");
    expect(typeof tokenjuice?.reducedChars).toBe("number");
  });

  it("leaves short / low-savings output alone", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const original = "hello";
    const output: FakeToolOutput = {
      title: "",
      output: original,
      metadata: {},
    };

    await hook(
      {
        tool: "bash",
        sessionID: "s1",
        callID: "c1",
        args: { command: "printf 'hello'" },
      },
      output,
    );

    expect(output.output).toBe(original);
    expect(output.metadata.tokenjuice).toBeUndefined();
  });

  it("skips file-content inspection commands like cat", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const verbatim = "export function reduceExecution() {}\n".repeat(40);
    const output: FakeToolOutput = {
      title: "",
      output: verbatim,
      metadata: {},
    };

    await hook(
      {
        tool: "bash",
        sessionID: "s1",
        callID: "c1",
        args: { command: "cat src/core/reduce.ts" },
      },
      output,
    );

    expect(output.output).toBe(verbatim);
    expect(output.metadata.tokenjuice).toBeUndefined();
  });

  it("prefers the trusted full output file when bash truncates", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const fullOutputPath = join(home, "bash-full.txt");
    const fullLines: string[] = [];
    for (let i = 0; i < 400; i += 1) {
      fullLines.push(`/etc/full/path/entry-${i}.conf`);
    }
    const fullText = `400 items\n${fullLines.join("\n")}\n`;
    await writeFile(fullOutputPath, fullText, "utf8");

    const visibleTruncated = [
      "...output truncated...",
      `Full output saved to: ${fullOutputPath}`,
      "",
      "400 items",
      "/etc/full/path/entry-397.conf",
      "/etc/full/path/entry-398.conf",
      "/etc/full/path/entry-399.conf",
    ].join("\n");

    const output: FakeToolOutput = {
      title: "",
      output: visibleTruncated,
      metadata: {
        truncated: true,
        outputPath: fullOutputPath,
      },
    };

    await hook(
      {
        tool: "bash",
        sessionID: "s1",
        callID: "c1",
        args: { command: "find /etc -maxdepth 6 -type f" },
      },
      output,
    );

    expect(output.output).toContain("tokenjuice compacted bash output");
    expect(output.output).toContain(`full output: ${fullOutputPath}`);
    const tokenjuice = output.metadata.tokenjuice as Record<string, unknown> | undefined;
    expect(tokenjuice?.compacted).toBe(true);
    expect(typeof tokenjuice?.rawChars).toBe("number");
    expect(tokenjuice?.rawChars as number).toBeGreaterThanOrEqual(fullText.length);
    expect(tokenjuice?.savedChars as number).toBeGreaterThan(0);
  });

  it("surfaces a clear error when the truncated outputPath cannot be read", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const missingPath = join(home, "does-not-exist.txt");
    const output: FakeToolOutput = {
      title: "",
      output: "...output truncated...\n\nFull output saved to: " + missingPath,
      metadata: {
        truncated: true,
        outputPath: missingPath,
      },
    };

    await expect(
      hook(
        {
          tool: "bash",
          sessionID: "s1",
          callID: "c1",
          args: { command: "find /usr/share -maxdepth 5 -type f" },
        },
        output,
      ),
    ).rejects.toThrow(/failed to stat bash full output file/);
  });

  it("skips compaction when the truncated outputPath is oversized", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const hugePath = join(home, "huge-output.txt");
    // 8 MiB + 1 byte - one byte over MAX_TRUSTED_FULL_OUTPUT_BYTES in runtime.
    const oversizedSize = 8 * 1024 * 1024 + 1;
    const chunk = "x".repeat(64 * 1024);
    const chunksNeeded = Math.ceil(oversizedSize / chunk.length);
    const pieces: string[] = [];
    for (let i = 0; i < chunksNeeded; i += 1) {
      pieces.push(chunk);
    }
    const bigBlob = pieces.join("").slice(0, oversizedSize);
    await writeFile(hugePath, bigBlob, "utf8");

    const visible = "...output truncated...\n\nFull output saved to: " + hugePath;
    const output: FakeToolOutput = {
      title: "",
      output: visible,
      metadata: {
        truncated: true,
        outputPath: hugePath,
      },
    };

    await hook(
      {
        tool: "bash",
        sessionID: "s1",
        callID: "c1",
        args: { command: "find /" },
      },
      output,
    );

    // Oversized path should not be trusted: no compaction, no tokenjuice metadata.
    expect(output.output).toBe(visible);
    expect(output.metadata.tokenjuice).toBeUndefined();
  });

  it("handles truncated:true without outputPath by skipping file trust", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    // Enough rows that git/log-oneline reducer will still fire on the visible text.
    const lines: string[] = [];
    for (let i = 0; i < 30; i += 1) {
      lines.push(`${i.toString(16).padStart(7, "0")} commit subject ${i}`);
    }
    const visible = `30 commits\n${lines.join("\n")}`;

    const output: FakeToolOutput = {
      title: "",
      output: visible,
      metadata: {
        truncated: true,
        // outputPath deliberately missing
      },
    };

    await hook(
      {
        tool: "bash",
        sessionID: "s1",
        callID: "c1",
        args: { command: "git log -30 --oneline" },
      },
      output,
    );

    expect(output.output).toContain("tokenjuice compacted bash output");
    // No "full output: ..." attribution because we never got a path.
    expect(output.output).not.toContain("full output:");
    expect(output.metadata.tokenjuice).toBeDefined();
  });

  it("ignores outputPath when truncated is not set", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const output: FakeToolOutput = {
      title: "",
      output: "hello",
      metadata: {
        truncated: false,
        outputPath: "/nonexistent/path/should-not-be-read.txt",
      },
    };

    await hook(
      {
        tool: "bash",
        sessionID: "s1",
        callID: "c1",
        args: { command: "echo hello" },
      },
      output,
    );

    expect(output.output).toBe("hello");
    expect(output.metadata.tokenjuice).toBeUndefined();
  });

  it("preserves null / missing metadata by attaching a fresh object", async () => {
    const home = await createTempDir();
    const extensionPath = join(home, "tokenjuice.js");
    await installOpenCodeExtension(extensionPath, { local: true });
    const hook = await loadInstalledHook(extensionPath);

    const output = {
      title: "",
      output: [
        "On branch main",
        "",
        "Changes not staged for commit:",
        "\tmodified:   foo.ts",
        "\tmodified:   bar.ts",
        "",
        "no changes added to commit",
      ].join("\n"),
      metadata: null as unknown,
    };

    await (hook as unknown as (i: FakeToolInput, o: { output: string; metadata: unknown }) => Promise<void>)(
      {
        tool: "bash",
        sessionID: "s1",
        callID: "c1",
        args: { command: "git status" },
      },
      output,
    );

    expect(output.output).toContain("tokenjuice compacted bash output");
    expect(output.metadata).toMatchObject({
      tokenjuice: expect.objectContaining({ compacted: true }),
    });
  });
});
